import groovy.xml.XmlUtil

node {
    String xmlContent = '''<?xml version='1.0' encoding='UTF-8'?>
<flow-definition plugin="workflow-job@2.9">
  <keepDependencies>false</keepDependencies>
  <properties>
    <org.jenkinsci.plugins.workflow.multibranch.BranchJobProperty plugin="workflow-multibranch@2.9.2">
      <branch plugin="branch-api@1.11.1">
        <sourceId>3b749ee0-a574-47d8-84cb-5bfe505836de</sourceId>
        <head plugin="scm-api@1.3">
          <name>pipe</name>
        </head>
        <scm class="hudson.plugins.git.GitSCM" plugin="git@3.0.1">
          <configVersion>2</configVersion>
          <userRemoteConfigs>
            <hudson.plugins.git.UserRemoteConfig>
              <name>origin</name>
              <refspec>+refs/heads/*:refs/remotes/origin/*</refspec>
              <url>https://github.com/escoem/pipeline-global-library-examples.git</url>
              <credentialsId>local</credentialsId>
            </hudson.plugins.git.UserRemoteConfig>
            <hudson.plugins.git.UserRemoteConfig>
              <name>origin</name>
              <refspec>+refs/pull/*/head:refs/remotes/origin/pr/*</refspec>
              <url>https://github.com/escoem/pipeline-global-library-examples.git</url>
              <credentialsId>local</credentialsId>
            </hudson.plugins.git.UserRemoteConfig>
          </userRemoteConfigs>
          <branches class="singleton-list">
            <hudson.plugins.git.BranchSpec>
              <name>pipe</name>
            </hudson.plugins.git.BranchSpec>
          </branches>
          <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
          <submoduleCfg class="empty-list"/>
          <extensions/>
        </scm>
        <properties class="java.util.concurrent.CopyOnWriteArrayList"/>
      </branch>
    </org.jenkinsci.plugins.workflow.multibranch.BranchJobProperty>
    <com.cloudbees.opscenter.analytics.reporter.items.AnalyticsJobProperty plugin="operations-center-analytics-reporter@2.32.0.1">
      <created>1485455766682</created>
    </com.cloudbees.opscenter.analytics.reporter.items.AnalyticsJobProperty>
  </properties>
  <definition class="org.jenkinsci.plugins.workflow.multibranch.SCMBinder" plugin="workflow-multibranch@2.9.2"/>
  <triggers/>
</flow-definition>'''
    
    
    def xml = new XmlSlurper().parseText(xmlContent)   
    println xml
    def newResult=XmlUtil.serialize(xml)    
    
}
